version: '3.8'

services:
  flask-app:
    build:
      context: ./flask_app
    ports:
      - "${FPORT}:${FPORT}"
    environment:
      - PORT=${FPORT}
    networks:
      - app-network

  nodejs-app:
    build:
      context: ./node_app
    ports:
      - "${NPORT}:${NPORT}"
    environment:
      - PORT=${NPORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
