version: '3.8'

services:
  flask-app:
    build:
      context: ./flask_app
    ports:
      - "5000:5000"
    networks:
      - app-network

  nodejs-app:
    build:
      context: ./node_app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
